# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
SO-100 / SO-101 Modality Configuration

6-DOF single-arm follower (5 arm joints + gripper), joint-position control:
- state/action = [shoulder_pan, shoulder_lift, elbow_flex, wrist_flex,
                  wrist_roll, gripper] -> single_arm[0:5] + gripper[5:6]
- Two RGB cameras (short names come from meta/modality.json)

Pairs with meta/modality.json generated by
run_scripts/data/make_so_modality.py. If your dataset uses different camera
names, edit the video modality_keys below to match.
"""

from rldx.configs.data.embodiment_configs import register_modality_config
from rldx.data.embodiment_tags import EmbodimentTag
from rldx.data.types import (
    ActionConfig,
    ActionFormat,
    ActionRepresentation,
    ActionType,
    ModalityConfig,
)


so101 = {
    "video": ModalityConfig(
        delta_indices=[0],
        modality_keys=["arm", "overview"],  # short names from meta/modality.json
    ),
    "state": ModalityConfig(
        delta_indices=[0],
        modality_keys=["single_arm", "gripper"],
    ),
    "action": ModalityConfig(
        delta_indices=list(range(0, 16)),
        modality_keys=["single_arm", "gripper"],
        action_configs=[
            # single_arm: absolute joint-position targets (not a 6DOF EEF pose).
            ActionConfig(
                rep=ActionRepresentation.ABSOLUTE,
                type=ActionType.NON_EEF,
                format=ActionFormat.DEFAULT,
            ),
            # gripper: absolute position target.
            ActionConfig(
                rep=ActionRepresentation.ABSOLUTE,
                type=ActionType.NON_EEF,
                format=ActionFormat.DEFAULT,
            ),
        ],
    ),
    "language": ModalityConfig(
        delta_indices=[0],
        modality_keys=["task"],  # synthesized from tasks metadata by LeRobotEpisodeLoader
    ),
}


register_modality_config(so101, EmbodimentTag.GENERAL_EMBODIMENT)
